### ISSUE TITLE
Issus in Nuget package?

### ISSUE THREAD

**Issue by MysticEmpires** [Yortw/tweetmoasharp#13]
Since Nuget Update to 3.1 i got errors on UAP-Projects while Newtonsoft.Json it self is installed with nuget. U can simply reproduce it:

- Create new UAP-Projects in VS2015 (RTM)
- Install Newtonsoft.Json with nuget (atm 7.0.1)
- Install TweetMoaSharp
- Run

Sorry for the german Error-Messages :)

![error](https://cloud.githubusercontent.com/assets/5948144/9157212/4d53b0ca-3ef5-11e5-9c9a-4345e17655e8.PNG)

**Comment by Yortw** [comment]
Hmmm. The Nuget package seems to be including the Json.Net binaries directly, as well as listing Json.Net as a dependent package. The nuspec file I use is a copy of the original TweetSharp one with edits made to version/author etc. but not the contents, so I presume this is a legacy problem that's only shown up now.

I've updated the nuspec file so it explicitly excludes the newtonsoft files, and it seems to work in a UWP app for me now. I've published this as version 3.0.0.6 on Nuget, so give that a try. Please let me know if it solves your problem or not, so I can close the issue.

One more thing - I'm having some issues myself with new package versions not showing up in Nuget on VS2015. It seems to be related to the Nuget v3 api. If you add a package source for the older Nuget v2 api then the new version shows up and downloads fine. If you can't see 3.0.0.6 in VS, try switching to the older api source.

**Comment by Yortw** [comment]
PS: Thanks for reporting the issue.

**Comment by MysticEmpires** [comment]
I will test it later at home and post the feedback. But this should be resolve the issue.

And yes that's a bug in github it self. If i'm not wrong, the issue is also reported here:

https://github.com/NuGet/Home/issues/1096

**Comment by Yortw** [comment]
Thanks for the link to the Nuget issue. I think I'm seeing this in multiple packages, although one of them might be suffering from the 'corrupt lucene index' also mentioned in the thread. Either way, good to know it's been reported.

**Comment by MysticEmpires** [comment]
Yes it's fixed the issus (but i have inlucde the v2 api source to get the newest Version ^^)

**Comment by Yortw** [comment]
Thanks for letting me know. I believe the NuGet team are working on the index/caching issue.
