### ISSUE TITLE
Low quality TwitterUser.ProfileImage

### ISSUE THREAD

**Issue by harrymilnes** [Yortw/tweetmoasharp#19]
TwitterUser.ProfileImageUrl & TwitterUser.ProfileImageUrlHttps both provide links to low quality images, the simplest fix would be to remove "normal" from the end of the image url. (for example:  "...qHMSV-MU_normal.jpg" should become: "...qHMSV-MU.jpg"

See https://dev.twitter.com/overview/general/user-profile-images-and-banners for details on profile avatar image sizing.

**Comment by Yortw** [comment]
I've been thinking about this and I'm still unsure about whether to change it. The values returned are the values that come from the Twitter API for this end point. If we change it, then it really should be documented as being different from the normal Twitter response, and then we're responsible for maintaining that documentation (not to mention no one will read it and we'll get question about why the vaule doesn't match the raw call. Hard to argue we're a 'thin wrapper around the Twitter API' if we start modifying the return values like this.

Additionally, I fear there may be existing clients that rely on the current behaviour. Would not be unlikely for someone to be retrieving the url and modifying it to get a smaller or larger image by replacing _normal in the string. Worse, simply dropping the _normal as suggested will return the original size image, which could be much larger than clients expect based on the existing behaviour which presumably returns a reasonable compromise between size and quality.

At this point, my suggest is that if you want the higher res version you use TweetSharp/TweetMoaSharp to retrieve the _normal version of the image and then modify the url yourself, as per Twitter's instructions, before retrieving the image.

True, TweetMoaSharp could provide a separate function to do the url conversion for you (and perhaps should?), but I don't think changing the value returned by these calls is a good idea, and modifying the url yourself shouldn't be too hard.

**Comment by harrymilnes** [comment]
Fair enough, I've been doing a string replacement on it but thought I'd just put this out there as an issue..

Thanks for getting back to me :)

**Comment by Yortw** [comment]
Thank you for the suggestion, sorry I chose not to action this one.
