### ISSUE TITLE
DeleteTweet should use POST

### ISSUE THREAD

**Issue by calbucci** [Yortw/tweetmoasharp#2]
The DeleteTweet functionality should use HTTP POST, not the DELETE method.

**Comment by Yortw** [comment]
Hi,

I really, sincerely, appreciate your collaboration. Thanks for taking the time to fork the repository, modify it, and submit a PR. That's fantastic.

Unfortunately the changes submitted weren't sufficient to fix the problem. The TwitterService.generated.cs file that was edited is (as the name implies and  the comment at the top of the file says) generated from a template. Modifying this file without modifying the template ensures the changes will be lost in future versions. There was also no unit test added to cover this case (and indeed, no unit test existed for delete status at all).

To that end I have modified the PR before merging it, so the T4 template that generates the .cs file now includes the correct verb too, and the method is unit tested. The code is now available in the master branch but I have not pushed an update to Nuget yet as there are some other issues I want to look at first. I *hope* to do that this weekend.

Thanks again, your work is appreciated.

**Comment by calbucci** [comment]
I suspected as much. Thank you.
