### ISSUE TITLE
Any change of a NET46 build?

### ISSUE THREAD

**Issue by calbucci** [Yortw/tweetmoasharp#20]
All is working well, it's just that Visual Studio keeps complaining about conflicts between different versions of the same dependent assembly.

**Comment by Yortw** [comment]
Hi,

Exactly what warnings are you getting? I created a brand new .Net 4.6 console app, added the package from nuget and built for both debug & release, and didn't get any complaints about mismatched assemblies. 

A 4.6 build is defintely possible, but I'd prefer not to if it's not actually neccesary/going to fix the problem.

**Comment by calbucci** [comment]
Troy, I believe the problem occurs when some of the dependencies of tweetmoasharp are upgraded.

**Comment by Yortw** [comment]
Thanks, but I am still struggling to reproduce this. The only dependency is json.net, and I just upgraded my test console app to 7.01 of that and I still don't get any warnings on build.
Any chance you could send me a project the reproduces the issue? Which version of VS are you using?

**Comment by Yortw** [comment]
Does this possibly relate to #24 ?

**Comment by calbucci** [comment]
I don't have this problem anymore. It was probably related to another package and a common dependency.

**Comment by Yortw** [comment]
:+1:
