### ISSUE TITLE
How I get users who retweeted my tweet?

### ISSUE THREAD

**Issue by knight7024** [Yortw/tweetmoasharp#26]
I wanna make RT'ers extractor

**Comment by Yortw** [comment]
Hi,

Glad you're interested in TweetMoaSharp. Here's some stuff that might get you started;

General Twitter API documentation: https://dev.twitter.com/rest/public
Note that TweetMoaSharp/TweetSharp have methods on the TwitterService class with very similar names to the Twitter Api endpoints. If you can figure out what/how to do what you want with the Twitter API it's usually very easy to find the relevant method in our libraries. Also, see the readme.md file in the repo for samples on how to handle auth and sample calls.

For your specific requirement, once you know the Id of the original tweet you want retweets of, the end point you need is; https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid - this is available in TweetMoaSharp as TwitterService.Retweets. Once you have a successfully authorised instance of a TwitterService object (assume it's called ts) you can call this method like this (sample uses 1 as original tweet id and assumes you have async/await support in your platform);

await ts.Retweets(new TweetSharp.RetweetsOptions( {  Id = 1 }));

Note that Twitter themselves limit the API to returning at most 100 retweeters. There is no easy/practical way to get more than the last 100 retweeters for any given tweet. Not a limitation of TweetSharp or TweetMoaSharp, but a limitation of Twitter's API.

Good luck.

**Comment by knight7024** [comment]
thanks for your help
i did it by :
            IEnumerable<TwitterStatus> Retweet_= service.Retweets(new RetweetsOptions { Id = ?, Count = 100 });
            foreach (var tweet in Retweet_)
            {
                listBox1.Items.Add(tweet.User.ScreenName);
            }

p.s. i found twitter api has cursor to allow paging back and forth. is tweetmoasharp impossible to cursoring?

**Comment by Yortw** [comment]
Some of the TweetSharp methods allow cursors, but I'm not sure if that one does or not. If you can't find it then probably not. Since its limited to 100 results its sort of questionable as to its value anyway, but I'd be happy to accept a pull request if anyone wants to submit one.
