### ISSUE TITLE
Missing Lists API

### ISSUE THREAD

**Issue by calbucci** [Yortw/tweetmoasharp#27]
It would be great if we could add two Lists API missing: 1) Ownerships (lists I own), and 2) members/create_all to add many members to a list at once.

I was trying to make these changes myself and send a PR, but I'm having a hard time with Hammock.

https://dev.twitter.com/rest/reference/post/lists/members/create_all

https://dev.twitter.com/rest/reference/get/lists/ownerships

**Comment by Yortw** [comment]
It's best to add Hammock as a submodule if you can (I don't have instructions sorry).

I'll see what I can do about adding these myself, as time allows.

**Comment by calbucci** [comment]
Thanks. I'll give it a try this weekend and if I make it work I'll send you a PR. Is it the JSON files where the changes should be made?

**Comment by Yortw** [comment]
Yeah. Assuming there's no complexity the T4 template can't handle, modify the json files and run the T4 template (there's an option to run it on the context menu in solution explorer IIRC). That should generate the new methods. The syntax is a ltitle arcane, but copy and paste should get you most of the way there :)

**Comment by Yortw** [comment]
I think I've got those two methods working. Have just pushed an updated nuget, let me know how that works for you.
