### ISSUE TITLE
lists/update api is not implemented

### ISSUE THREAD

**Issue by calbucci** [Yortw/tweetmoasharp#29]
From: https://dev.twitter.com/rest/reference/post/lists/update

Enable lists to update title & description. I believe the right syntax for T4 is this:

TwitterList, "lists/update":POST, UpdateList, string owner_screen_name, long? owner_id, long? list_id, string slug, TwitterListMode? mode, string name, string description

Thank you.

**Comment by calbucci** [comment]
Sent PR #30

**Comment by Yortw** [comment]
Changes merged and push to nuget. Thanks for your hard work!
