### ISSUE TITLE
ListDirectMessagesSent() does work ?

### ISSUE THREAD

**Issue by andreibudea** [Yortw/tweetmoasharp#32]
I've been trying for days to get the list of the direct messages that I have and it doesn't do anything,it works or is just deprecated ?

Thank you!

**Comment by Yortw** [comment]
The unit tests pass and I just wrote some sample code using my own account, and that also works fine.
Are you sure your user token grants you access to direct messages?
Have you checked the Response property of the TwitterService instance after calling ListDirectMessagesSent to find out what the response from twitter was? Was is the status code/reason phrase/content of the response?

**Comment by andreibudea** [comment]
My service just gives me null, I sent private messeges,tweets and read tweets all works fine, but I can´t get the the list of private messages.
And I'm using all 2 keys and 2 tokens that twitter give you .
`   var OAuthConsumerKey = "*";
    var OAuthConsumerSecret = "*";
    var OAuthToken = "734733609320501248-*";
    var OAuthTokeySecret = "*";
   TwitterUser user = twitterApp.VerifyCredentials(new VerifyCredentialsOptions());
  var message = twitterApp.ListDirectMessagesReceived(new ListDirectMessagesReceivedOptions());`

**Comment by Yortw** [comment]
I understand the result of the method call is null, but after you make the call the *Response* property on the twitter service object should contain the raw response from the Twitter API. What does it tell you?

It's working for me under two different accounts, so while there could be a problem in the library I'm guessing it's something related to your code/setup/security etc.

**Comment by andreibudea** [comment]
Response = "{\"errors\":[{\"code\":93,\"message\":\"This application is not allowed to access or delete your direct messages.\"}]}"
I have "Read, Write and Access direct messages" permissions activated and I get this message.

**Comment by Yortw** [comment]
Ok, well that's definitely an error back from the Twitter API, saying you don't have permission, not an error from a library. It is working for me with two separate accounts so I think the auth in the library is ok. I'm not sure what to suggest. It seems like your auth token doesn't have permission but you claim it does.

Perhaps you should read https://dev.twitter.com/oauth/overview/application-permission-model and see if it helps.

Also, did you perhaps enable direct messages on your app record after you first created the user auth token? That link specifically says it won't affect existing tokens. If that's the case, you probably need to create a new auth token for the user account now that the app is already set to allow direct message access.

That link also suggests checking the X-Access-Level (in the response property you've already checked), make sure that says direct messages are supported.

**Comment by Yortw** [comment]
Did some other work on the library and can confirm the ListDirectMessagesSent method does work, at least for the test account and my personal account. I don't get any error response like you are, so it definitely looks related to your tokens/account security somehow.

**Comment by collinsauve** [comment]
FYI I've been using ListDirectMessagesSentAsync without issue.

For some stats:  In the past 24 hours:

* We successfully pulled DMs for 3056 users in the past 24 
* We failed to pull DMs for 2 users due to their accounts being locked (code 326)

We are currently using TweetMoaSharp v3.0.0.15.

**Comment by Yortw** [comment]
Closing as this doesn't appear to be a problem with the library.
