### ISSUE TITLE
Missing media/upload chunked API

### ISSUE THREAD

**Issue by StevenTsvetkov** [Yortw/tweetmoasharp#33]
From what I can tell, the different stages for chunked media upload endpoint are not implemented. More information on that here: https://dev.twitter.com/rest/reference/post/media/upload-init

With the current implementation, I cannot find a way to upload MP4 video files, as the normal media/upload endpoint is limited to only images. Is there a workaround?

Thanks!

**Comment by Yortw** [comment]
Hi,

I was away for a long weekend, so only just noticed this, sorry.
Thanks for reporting it, you are correct, those methods are missing. I will look at adding them as time allows, but to be honest this project isn't my current focus right now and I have very limited time, so I can't promise when I'll get to it.

Good pull requests always appreciated :)

**Comment by Yortw** [comment]
FYI, have spent a number of hours on this, but it is more difficult than I expected. The existing T4 template engine isn't really setup for it, and there's lots of special handling around uploading 'media' files in TS/Hammock that doesn't work especially well in this scenario. I'll keep working on it, but I wouldn't expect it any time soon. PR's are welcome if you or someone else can get it working before I do.

**Comment by Yortw** [comment]
Possibly the only thing I hate more than the Twitter API is the Twitter API Documentation. These endpoints suck, and the documentation is worse. I *think* I had it working barring one small issue, which I have now resolved, but in my quest for that solution I appear to have broken something else that was working, and I don't know what.

Yay for the largely undocumented media_category enum on the INIT call.

I'm still working on this. Will advise if I come up with a solution.

**Comment by Yortw** [comment]
This should now be supported in the 3.0.0.22 release. Please also see https://github.com/Yortw/tweetmoasharp/wiki/Chunked-Media-Upload-Tips
