### ISSUE TITLE
Incompatible with .Net Core 1.0

### ISSUE THREAD

**Issue by bhasden** [Yortw/tweetmoasharp#34]
I'm putting together a test/example .NET Core app and am having issues using your library. When adding TweetMoaSharp from NuGet I get the following output from the Package Manager. 

    Package TweetMoaSharp 3.0.0.15 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package TweetMoaSharp 3.0.0.15 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
      - sl4 (Silverlight,Version=v4.0)
      - sl4-wp (Silverlight,Version=v4.0,Profile=WindowsPhone)
      - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Any suggestions on how to get the library working properly in .NET Core 1.0 or are there dependencies that make it impossible?

**Comment by Yortw** [comment]
I'm afraid I've never tried it with .Net Core. It's not a target I was particularly worried about, and I've been waiting for it to release/settle down before I look at adding support in any of my libraries.

It *might* work if you manually download the package, unzip the contents and reference the .Net 4.5 assemblies.
If it does, then it's just a packaging issue and I could look at updating the package to include support. Otherwise, it will likely need a bit more work and I'm not sure when I'll have time.

**Comment by Yortw** [comment]
I've spent 2 hours trying to work on this, but I can't even create a new .Net Core project. All the RC2 tools appear to be installed, but both the VS integration and the command line fail at the restore and then build steps. Since I can't even create a project (and I'm out of time for the foreseeable future) I'm not likely to be able to help much in the short term. Maybe when the tools are officially published (and hopefully work).

**Comment by bhasden** [comment]
Sorry for the delayed response. I created a .NET Core project and added the links to the actual source files (like the other projects) and everything seems to compile properly, so it looks like the library would work with .NET Core if I could figure out how to publish it with the correctly targeted runtime.

I have spent the last few hours publishing NuGet packages and trying to figure out how to add support for .NET Core. I can't seem to figure out how to specify the targeted runtime. The only thing I ever get back from the VS2015 NuGet client is:

`Package TweetSharpTest 1.0.6 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package TweetSharpTest 1.0.6 supports: net (.NETFramework,Version=v0.0)`

Any suggestions would be greatly appreciated. If I get anything working I'd be happy to shoot a PR your way.

**Comment by Yortw** [comment]
I believe there used to be a project template for 'library with package' or similar name, that creates a .Net core class library project that generated a nuget package when built. If you can create and build one of those, we can open up the resulting nupkg file (its just a zip file) and see what the nuspec says in terms of targets etc. I am assuming .Net core libs still use a nuspec file in the latest nuget (and aren't totally project.json dependent).

Alternatively, the nuget docs here should list the appropriate targets; ttps://docs.nuget.org/Create/TargetFrameworks
It looks like netcore or netcore50 might be appropriate. I think I've also heard mention of netstandard so you could try that.

If you can post your current nuspec file (perhaps a gist or to pastebin, or just email it to me) then I can take a look and see if I can figure anything out.

**Comment by bhasden** [comment]
Thanks for the link to the target documentation. The `.nuspec` file I'm working with is pasted below. No matter what I do, I can't seem to get anything other than the following error out of nuget: `Package TweetSharpTest 1.0.11 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package TweetSharpTest 1.0.11 supports: net (.NETFramework,Version=v0.0)` I can't help but think there's something really simple I'm missing here.

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
        <metadata>
            <id>TweetSharpTest</id>
            <version>1.0.11</version>
            <authors>bhasden</authors>
            <requireLicenseAcceptance>false</requireLicenseAcceptance>
            <description>My package description.</description>
            <serviceable>false</serviceable>
            <dependencies>
                <group targetFramework="DNXCore5.0">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
                <group targetFramework=".NETCore5.0">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
                <group targetFramework="DNX4.5.2">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
            </dependencies>
        </metadata>
    </package>`

**Comment by Yortw** [comment]
You don't appear to have a 'files' section, so there's no content in the package - that *might* be the issue.
Either add a files section (see the nuget docs) and explicitly include your .netcore compiled dll from your source, installing to the appropriate targets folder, or to follow what TweetSharp/TweetMoaSharp do;

```xml
	<files>
	  <file src="**\*.*" exclude="**\Newtonsoft.*" />
	</files>
```

but then ensure your dll is being built in lib\netcore50 inside the project tree so nuget knows where to install it to. 

You could also try using 'Nuget Package Explorer' which is a GUI tool for building packages, but you'll still need to add a lib folder and add your dll into the appropriate subfolder.

I actually think *lib\netstandard1.0* (or a higher version if required) looks like the right target based on that tool.

**Comment by bhasden** [comment]
Sorry for the confusion. I'm actually using the NuGet Package Explorer which I thought was showing me the entire `.nuspec` file when I clicked on the "Edit Metadata Source". I've repasted the entire file below with the addition of the netstandard1.0 framework.

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
        <metadata>
            <id>TweetSharpTest</id>
            <version>1.0.13</version>
            <authors>bhasden</authors>
            <requireLicenseAcceptance>false</requireLicenseAcceptance>
            <description>My package description.</description>
            <serviceable>false</serviceable>
            <dependencies>
                <group targetFramework="DNXCore5.0">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
                <group targetFramework=".NETCore5.0">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
                <group targetFramework="DNX4.5.2">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
                <group targetFramework=".NETStandard1.0">
                    <dependency id="Newtonsoft.Json" version="8.0.3" />
                </group>
            </dependencies>
        </metadata>
        <files>
            <file src="TweetSharp.NetCore.dll" target="lib\TweetSharp.NetCore.dll" />
        </files>
    </package>

**Comment by Yortw** [comment]
I think you need;

```xml
    <files>
        <file src="TweetSharp.NetCore.dll" target="lib\netstandard1.0\TweetSharp.NetCore.dll" />
    </files>
```
instead of just putting your dll directly into lib - I don't think nuget will know which platform without the subfolder (but I'm no expert).

**Comment by bhasden** [comment]
Welp, that was the obvious thing that I was missing. For anyone that comes across this at a later date, if you right click in the "Package contents" area there's an entire context menu with options that are pretty self-explanatory.

Thank you so much for your help. I can confirm that the .NET 4.5 assemblies that get built as part of the TweetSharp.Net45 project will install correctly when used as part of a NuGet package targeting "netstandard1.0" like you mentioned. I haven't done any testing other than confirming that I can run my project and create an instance of the TwitterService class.

Once again, thanks for your help.

**Comment by Yortw** [comment]
No problem :) When I get some time I'll see if I can add the Net 4.5 assemblies into the nuget package for the netstandard1.0 target and let you know so you can try it from a netcore project.

**Comment by Yortw** [comment]
This should be closed by merging of pr/39.
Have published a new version of the nuget package to nuget.org which should add .NetCore support, and should be available in 15 minutes or so.

**Comment by Yortw** [comment]
BTW... thanks for the PR and all your help with this! 😄

**Comment by Stev3nT** [comment]
I was actually using this library with Core RC1 and RC2 and had no issues.

**Comment by Yortw** [comment]
Via the NuGet package, or did you manually ref one of the platform assemblies?

**Comment by bhasden** [comment]
I'm not super familiar with the specifics for the different types of .NET Core projects, but I can tell you that I'm not able to reference anything but .NET Framework assemblies from my .NET Core project (ASP.NET Core Web Application). Trying to reference the TweetSharp.dll file (and any other DLLs) results in the following error:

![image](https://cloud.githubusercontent.com/assets/175529/16329034/c4adb3b0-39ad-11e6-8661-9e096c33df0d.png)

The only way I was able to consume TweetMoaSharp was by modifying the NuGet package to add support for .NET Standard 1.0 like @Yortw suggested.

**Comment by Stev3nT** [comment]
My exact version is ASP.NET Core RC2 build 2702 and I am running an application with only the new project types and "compiling" dynamically with Roslyn. I'm using the latest version of TweetMoaSharp via NuGet with no problemo. You might want to check out the latest install executables https://www.microsoft.com/net/download for your respective platform architecture. You need both .NET Core and .NET Core SDK.

**Comment by Stev3nT** [comment]
Or just update it via visual studio if you deem fit. I rarely use Windows, I run a self-made development environment with Atom on Ubuntu 16. The NuGet package works fine on both operating systems.
