### ISSUE TITLE
Adding TweetMoaSharp via NuGet adds also a reference to NUnit

### ISSUE THREAD

**Issue by MarkLie** [Yortw/tweetmoasharp#40]
Hi community,

I was just wondering, why adding TweetMoaSharp to my C# project via NuGet also adds a reference to NUnit? Is this really necessary? I prefer to have production code and related unit tests in two different projects, so you can easily publish production code as NuGet package without a reference to unit test libraries.

Best Regards,
Mark

**Comment by collinsauve** [comment]
I **think** this is fixed via https://github.com/Yortw/tweetmoasharp/pull/38.

**Comment by MarkLie** [comment]
It looks like it is. Thank you for letting me know.
