### ISSUE TITLE
Uploading A Video As Media Won't Work

### ISSUE THREAD

**Issue by RayyanTahir** [Yortw/tweetmoasharp#42]
Hi Yortw, thank you for the time in maintaining a really nice C#.net wrapper for C# developers.

I was trying to upload a video using service.UploadMedia(Options) where Options contained the stream of my video file. The function returned null. It works for Images but not for videos. Please advise.

If there's no video uploading api wrapper yet, then please consider this as a feature request.

Many thanks,

**Comment by Yortw** [comment]
You're welcome, thanks for the kind words :)

I *believe* the API should work for video, though I've only tried it with animated gifs myself.
What format video did you try?
Did the Response property of your instance of TwitterService contain an error response after the method returned null?
Does the video meet Twitter's restrictions on length, size and type? Note I believe Twitter recently increased the maximum allowed size/length of video, but I've also read (unconfirmed) that the increase only applies to Twitter itself when using the Twitter website, anything using the API (including Twitter's own apps, apparently) is stuck with the old limits.

Any chance you could provide a link to the video so I can use it for testing?

Thanks.

**Comment by Yortw** [comment]
It's possible this doesn't work currently, and relates to #33 

https://dev.twitter.com/rest/reference/post/media/upload

**Comment by RayyanTahir** [comment]
Hi, Thank you for your reply. The video file i was trying to upload is of the format *.mp4. I have attached the file here for testing.
[video.zip](https://github.com/Yortw/tweetmoasharp/files/429769/video.zip)

Also, based on issue #33 , is there any chance we will be getting an updated API for chunk based uploads soon?

Appreciate your help. Thanks.

**Comment by Yortw** [comment]
Closing this as duplicate, see issue #33 for status instead.
