### ISSUE TITLE
Send Tweet with Multiple Images

### ISSUE THREAD

**Issue by Yortw** [Yortw/tweetmoasharp#5]
I believe Twitter implemented this after TweetSharp stopped being supported, so it probably doesn't work. We should implement this feature.

**Comment by Yortw** [comment]
Confirmed that while TweetSharp's API looks like it supports multiple images, and the call doesn't fail with an error, it doesn't work properly either. It appears Twitter just uses the last (single) media item in the post content.

According to Twitter's own documentation the method in use is now deprecated. Correct procedure is to call a separate endpoint once for each media item and track returned ids, then call normal status update method and pass captured id's. Will need to update TweetMoaSharp to support this.

**Comment by scorpionmit01** [comment]
If you use the UploadMedia method on an UploadMediaOption, you get back a String of the Media_Id.  I then stick them into a List.  That's in the TweetSharp code but not in any of the exampls.

**Comment by Yortw** [comment]
Yes, I updated the system to include the media id mechanism recently, but I haven't updated any of the samples (I presume you mean in the readme.md file?). If you want to submit some sample code & text I'm happy to update it.

**Comment by scorpionmit01** [comment]
I can try to update the readme.  I just started using it recently, great work!  I'll try to help on the documentation.

**Comment by Yortw** [comment]
Thanks, that would be helpful 😊
