### ISSUE TITLE
Upload media not working

### ISSUE THREAD

**Issue by heyou93** [Yortw/tweetmoasharp#50]
I cannot upload media and attach the mediaId with a tweet. It always return null for the uploadmedia method.

**Comment by Yortw** [comment]
Have you checked the Response property on the TwitterService object after your call? What is the response code, reason phrase and content of the response? That should tell you what the error is, or at least give you a clue about the problem.

The current unit tests for for those methods work, so I'm assuming it's a problem with the media you're trying to upload (or possibly some kind of auth issue etc). There are various limits on the media supported by Twitter. What kind of media is it it? If it's a video or large animated gif you might need to try the chunked upload (https://github.com/Yortw/tweetmoasharp/wiki/Chunked-Media-Upload-Tips). What file size is the media? What are the dimensions of the image or individual media frames?

Have you read the upload media guide from Twitter?
https://dev.twitter.com/rest/media/uploading-media

**Comment by Yortw** [comment]
Did you figure out what the problem was, or what error was being returned in the TwitterService.Response property?

**Comment by Yortw** [comment]
Closing as no response. Please re-open if new information is available.
