### ISSUE TITLE
Can't post to Twitter feed

### ISSUE THREAD

**Issue by fonix232** [Yortw/tweetmoasharp#51]
I'm using the latest TweetMoaSharp and am a bit baffled with this error.

It is in a server environment, where the client sends us the accessToken and accessTokenSecret to be stored online. I'm running the following code:

```
var service = new TwitterService("consumerKey", "consumerKeySecret");
service.AuthenticateWith("accessToken", "accessTokenSecret");
var result = service.SendTweet(new SendTweetOptions { Status = "Test post" });
```

However at the end, result is null, and the post does not appear.

**Comment by Yortw** [comment]
Hi,

Hard to help without knowing more about the error, I suspect it's a security related issue, but am not sure. After calling the service.SendTweet method, check the service.Response property. Specifically look for the http status code, reason phrase, and if the content is non-null/> 0 length, read it as a string and see what it says. That should give you a clue about what the error returned by Twitter was.

**Comment by Yortw** [comment]
Did you find out what the error was?

**Comment by Yortw** [comment]
Closing this due to lack of response. Please re-open if new information is available.
