### ISSUE TITLE
Chunked Media Upload - "Could not authenticate you"

### ISSUE THREAD

**Issue by RayyanTahir** [Yortw/tweetmoasharp#52]
Hi,

I've been trying to upload a gif image in a chunk based approach in the following way:
`var service = new TwitterService(_consumer_key, _consumer_secret);
 service.AuthenticateWith(AccessToken, AccessTokenSecret);

 var cMediares = await service.UploadMediaInitAsync(new UploadMediaInitOptions() { "image/gif", TotalBytes = 38656, MediaCategory = TwitterMediaCategory.AnimatedGif});`

But in response i'm getting an error, '**32: "Could not authenticate you."**' at service.UploadMediaInitAsync call.

Your kind help will be much appreciated.
Thanks.

**Comment by Yortw** [comment]
Hi,

Not sure what the problem is. Haven’t seen that error before and the unit tests are working for me on my test account.

Have you tried the code and gif from the TweetMoaSharp unit tests? See if that works for you first (with your tokens), maybe that will tell us something.

**Comment by RayyanTahir** [comment]
Thank you,

I did clone the src but I'm having build issues related to Hammock.

Thanks,

**Comment by Yortw** [comment]
Yeah, Hammock is a submodule and getting it setup can be awkward. I usually spend an hour or two with Google getting it right.

I suggest making a new (console?) project, adding the nuget package, copying the code & sample gif from the unit test into your new project and plugging in your tokens. It isn't neccesary to run the actual tests, just to use that code with your tokens as a starting point.

**Comment by RayyanTahir** [comment]
Thank you, I'll get back to you on this, once i'm done configuring and testing. Again thank you for your help.

**Comment by RayyanTahir** [comment]
Hi,

I've been trying to configure the console project as you suggested, I did manage to add all missing references/items but i'm getting syntax errors such as the ones attached here.
![syntax errors](https://cloud.githubusercontent.com/assets/1668183/19474034/53025752-9547-11e6-862e-98fc7498f54f.PNG)

Could you perhaps provide me with a working console project (as you suggested) where i could pass my tokens and test?

Thanks.

**Comment by Yortw** [comment]
Hi,

Test project at; https://1drv.ms/u/s!ArC3Ud4fUz-MgfX4K3cfpNsdyyb7Fqk

It does two things;

1. It runs the code from your original post (which just does the init call)
2. It does a full upload of an animated gif using the (slightly mondified) code from the unit tests

Here's the results I get from my test account tokens;

![tweetsharpresponse2](https://cloud.githubusercontent.com/assets/6725891/19548001/31b3a9e0-96f8-11e6-82de-ecf080ecca40.PNG)

Obviously I removed my tokens from the source.
The first line is the response from Twitter after running your original code (the init call)
The following lines are my test image actually being uploaded, first an init, the multiple chunk uploads, then a finalize, and finally the id of a (private) tweet posted with the image attached.

It all works for me, I'm wondering if there's something wrong with your stored tokens?

**Comment by RayyanTahir** [comment]
Hi Yortw,

Thank you so much for your time and support. I tested it, it appears that probably my application is blocked for some reason; because when i created a new application and tokens it worked perfectly.

Thank you again.

**Comment by Yortw** [comment]
No problem :)
