### ISSUE TITLE
How to use TwitterService.StreamFilter with options

### ISSUE THREAD

**Issue by gisfromscratch** [Yortw/tweetmoasharp#53]
Is it possible to specify any options with the filter. When I use this method the twitter endpoint is yelling at me: "No filter parameters found. Expect at least one parameter: follow track locations".

**Comment by Yortw** [comment]
It does look like there's any ability to pass options. I haven't worked on this method, so not sure if it used to work and Twitter's requirements have changed, or if it was never finished in the original TweetSharp.
StreamUser seems to work, but doesn't have the same parameter requirements.

I might look at it when I get some time, but can't promise when that will be. Good PR's are always appreciated if it's urgent for you.

**Comment by gisfromscratch** [comment]
Seems to work with a lil hack. I used the wrong ticket number in the following pushed commit.

https://github.com/gisfromscratch/tweetmoasharp/commit/e0c7a575c0246206f610886b7c0eb25b90b64cb0

**Comment by Yortw** [comment]
The streaming stuff looks like it's implemented in a simpler fashion than the rest. There's no T4 template or code generation involved. I'm working on a branch where all the streaming options (that don't require special access) are implemented for both stream types.

**Comment by Yortw** [comment]
I've published an update to Nuget (should be available in 15 mins or so) which includes an options parameter, containing most of the available Twitter options (I didn't impement the ones that require special permissions etc). That should make this feature work now. Thanks for the bug report and sample fix.
