### ISSUE TITLE
How can i undo self retweet?

### ISSUE THREAD

**Issue by knight7024** [Yortw/tweetmoasharp#58]
there is unretweet in official API but not in moasharp. I'm using delete api to undo retweet but it is not good for undo self retweet. Is it not added yet or not supported?

**Comment by Yortw** [comment]
Correct, that end point is not currently supported. I am not aware of another way of undoing a self-retweet. Previously I believe the Twitter docs said to delete the retweet, but that obviously doesn't work for self-retweets. This will need to be implemented in the library.

**Comment by Yortw** [comment]
Just pushed a new version to nugget which should fix this.

**Comment by knight7024** [comment]
thx
