### ISSUE TITLE
Posting Image along with summary and  URL

### ISSUE THREAD

**Issue by Dikshasoft** [Yortw/tweetmoasharp#65]
Hi,
I'm using TweetResharp to post an article on subscribed Twitter account. I'm able to post the tweet header and just Image. But I need to be able to post something like what i have attached. please let me know if we have this provision with TweetSharp?

![tw](https://user-images.githubusercontent.com/25227385/37347582-0efa8dc0-26ca-11e8-8111-2690795e78c0.GIF)

**Comment by Dikshasoft** [comment]
Thanks collinsauve,
I was able to use Open graph tag and reproduce this. TAHNKS. I'm curious, if this is possible to create similar structure using API input dynamically from c# (eg, image, summary and link would be provided in the api call itself)

**Comment by collinsauve** [comment]
There's a newer concept in the API called "cards", which may achieve what you're looking for - but I've personally never used them.

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by Dikshasoft** [comment]
Thanks Collinsauve,

I really appreciate you support here.

**Comment by collinsauve** [comment]
Oh my bad I think the "cards" concept is just a parallel to OG tags.  Looks like it allows you to show things other than just "article"s. 

I can't find anywhere that allows you to supply this information via the API POST though :(
