### ISSUE TITLE
Fetching 280 character tweets

### ISSUE THREAD

**Issue by SinaErem** [Yortw/tweetmoasharp#68]
Is any development being made in TweetMoaSharp to support fetching tweets longer than 140 characters ?(up to 280 characters, the current maximum)

**Comment by collinsauve** [comment]
Just add `TweetMode = "extended"` to the options object for whichever function you're using.

**Comment by SinaErem** [comment]
In TweetMoaSharp, there is no field <TweetMode> in SearchOptions. Would you please give an example of how to do it.

**Comment by Yortw** [comment]
Tweet mode is a property on the TwitterService instance, in your case it should be on the 'service' variable.

`c#
service.TweetMode = "extended";

options = new SearchOptions { ……  }
collection = service.Search(options);
`
