### ISSUE TITLE
Can't Tweet with Some Characters

### ISSUE THREAD

**Issue by Yortw** [Yortw/tweetmoasharp#7]
There is an issue in the original TweetSharp repository that suggests some characters cause tweets to fail. This is specifically listed as a problem when the tweet includes media, but may just be an issue with the character encoding regardless of what else in the tweet. A sample message that causes the problem is;

 "Hello à ...." 

There is also a suggestion that the apostrophe character ' may cause similar issues. To quote the original issue;

After search, I have immediately error if message contains ' (quote) character such as " L'image ". If I try the message " L image ", tweet will be send with no error.

**Comment by Yortw** [comment]
Have spent some time on this. Can confirm the accented a causes a problem, but only when also posting with an image. Posting a status without an image and an accented char works fine, as does posting a status with an image but no accent chars. Since the code is principally the same I am at a loss as to what the issue is, the problem chars seem to be correctly encoded everywhere. Based on the error returned (status = 401, unauthorised, error = 32, could not authenticate you) it appears to be a problem in Hammock with the auth header though that is still partly assumption.

The problems don't end there though. The endpoint currently used to upload a status with media is now deprecated. Apparently we should call a separate endpoint (once for each media item) and track the id's returned, then call the normal status update endpoint passing it the list of ids. We need to change to this mechanism to support multiple media upload anyway (I tested and while the existing TweetSharp API allows multiple media files to be included, Twitter seems to just use the last one in the post body).

Additional confusion occurs around the oauth header for the post anyway. According to Twitter's own documentation (https://dev.twitter.com/rest/public/uploading-media) the signature should *only* include the oauth parameters, and not the request parameters normally included (i.e status, include_entities etc). This seems fairly difficult to implement in Hammock as at the point where the auth header is constructed we haven't even decided that the post body is multipart form data. Worse, when I hack the code to force it to remove the extra parameters from the oauth signature base string Twitter starts returning an unauthorised response for calls that worked when the parameters were present. Of course that fact that it works when those parameters are present suggests that either I'm mis-reading Twitter's documentation or that Twitter is inconsistent with the oauth validation (which there is anecdotal evidence of on their support pages). Either way I haven't found an easy fix yet.

**Comment by jnccd** [comment]
Why did you close this? 
I am literally still getting this exact error

I haven't tried all you characters yet but a - or an empty text still produces that same error message

**Comment by Yortw** [comment]
Hi,

This was closed as the original report only affected a very specific API endpoint which Twitter themselves have deprecated. The library was updated to support the new API endpoints for uploading then tweeting media, and using that system (at the time) the same problem did not occur.

If your are experiencing exactly the same problem then you should change to using the new API, where media is uploaded first and then attached to the tweet via it's id. If you are experiencing the same *symptom* but not in the same way/context or using the same endpoint (i.e if this is now occurring with the new API), then a new issue would be appropriate.

PR's to solve problems are gratefully received, especially as I no longer have any projects using this library (or indeed Twitter) and so any time I spend on this is purely working for other people for free.

Thanks.

**Comment by jnccd** [comment]
Thanks for your reply,

I am actually using the new endpoint and still get the exact bug you got with the old api but I build a workaround that just replaces certain characters from the text payload now which works well enough for my usecase.

**Comment by Yortw** [comment]
Glad you have a work around, again if you find a proper fix a PR is appreciated.
Also please feel free to open a new issue specifying this happens with the new endpoint (sample tweet appreciated). That way I can look if I find time (ha ha) or someone else can, and at least the problem is documented for others.
