### ISSUE TITLE
No rate limiting feedback

### ISSUE THREAD

**Issue by acohenX1** [Yortw/tweetmoasharp#73]
I've been stumped for a little bit trying to figure out why I'm only able to retrieve 15 of an account's 16 direct messages. I finally found that in the API there's a rate limit on the endpoint of 15 calls every 15 minutes (https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/get-event.html)

Instead of getting an object back containing the error information, I'm getting back `null` from `GetDirectMessage`. The json coming back through `TwitterService#WithHammockImpl<T>` has all of the relevant information.

    {"errors":[{"code":32,"message":"Could not authenticate you."}]}

Obviously this is for a different error, but it still results in a null return value for `GetDirectMessage`.

Using the v5.2.0 of the .NET 4.5 version of the API.

**Comment by Yortw** [comment]
My memory of how TweetSharp works is foggy, I may have this wrong, but I think this is normal for most TweetSharp methods. If the response is an API error (as opposed to a network error etc), no exception is thrown and a null result is returned. You can check the response and error details by looking at the Response property on the TwitterService object. That's not great in multi-threaded apps (unless every thread/call has it's own service object), so I think I included in the response on the result objects returned by the latest task based async actions.

TBH, it's not what I think is a good idea (it's pretty horrible, actually). There probably should be a TweetSharpException or TwitterApiException which is thrown when the API returns a failure, but I believe this part of the design predates me picking up support for the library and I haven't had time or inclination to fix.

I believe the response property on the service object also includes rate limiting data (I've had to fix the original a couple of times to deserialise it properly).

Pull requests appreciated.

**Comment by acohenX1** [comment]
The Service Response object is good enough! Thank you.

**Comment by Yortw** [comment]
No problem :)
