### ISSUE TITLE
ListDirectMessageOptions.Cursor is the wrong data type

### ISSUE THREAD

**Issue by acohenX1** [Yortw/tweetmoasharp#74]
`ListDirectMessageOptions.Cursor` is a `long?` however the data I get back for `TwitterDirectMessageListResult.NextCursor` is a `string` like `MTA1NDUzNzI1MDc3ODcwMTgyOQ`.

**Comment by Yortw** [comment]
Sigh. It seems the new API is inconsistent with the old API, and I had assumed the same type used for other twitter cursors would work.

Not sure what to do about this. Either need to convert the existing type to use strings, which is a breaking change and may or may not be cool going forward, or invent a new type that is used only by the direct message API. Either way I'm not sure when I'll get to this sorry.

**Comment by acohenX1** [comment]
For what it's worth, modifying `src/TweetSharp/_TwitterService.5.DirectMessages.json` did the trick in my fork (I'm not able to test all configs, however, just using .NET 4.5):

    //GET direct_messages/events/list (get set of dms)
    TwitterDirectMessageListResult, "direct_messages/events/list", ListDirectMessages, long? count, string cursor

**Comment by Yortw** [comment]
Hi, sorry it's taken so long, am looking at fixing this now.

It seems I already got the correct data type for the cursor on *TwitterDirectMessageListResult* which I had assumed needed to be changed, so it should only be the method you've indicated that needs updating. Unfortunately still a breaking changes to the interface, so will need a major version bump...

**Comment by Yortw** [comment]
Should be fixed in version 6, just published to Nuget now.
