### ISSUE TITLE
Tweetmoasharp works locally but not remotely

### ISSUE THREAD

**Issue by Sinan-Noureddine** [Yortw/tweetmoasharp#77]
I've been using Tweetmoasharp library to post to Twitter for over a year now. The library suddenly stopped working on my online website 2 weeks ago. However, when i run the code locally, the library is working perfectly.

Code:-

        Dim TwitterConsumerKey = "XXX"
        Dim TwitterConsumerSecret = "XXX"
        Dim TwitterToken = "XXX"
        Dim TwitterTokenSecret = "XXX"
        Dim twitter = New TwitterService(TwitterConsumerKey, TwitterConsumerSecret, TwitterToken, TwitterTokenSecret)

        Dim sto = New SendTweetOptions
        sto.Status = Left(title, 140).Trim ' max tweet length; tweets fail if too long...
        Dim twitterStatus = twitter.SendTweet(sto)
        If twitterStatus IsNot Nothing Then
            ' tweet sent
            'Hitting this part Locally!
            Return True
        Else
            ' tweet failed
            'Hitting this part remotely!
            Return False
        End If

Any suggestions?

**Comment by collinsauve** [comment]
Which OS and .Net versions are you using in the two different environments?

**Comment by Sinan-Noureddine** [comment]
Locally, I am using the library on Windows 7 .net framework 4.6.1
Online, I am using the library on Windows 7 .net framework 4.5.2

It was actually working perfectly on both (locally and online) but it suddenly stopped working online. It might be related to the update that twitter published 2 weeks ago.

Please advise.

**Comment by collinsauve** [comment]
Its probably this issue: https://github.com/Yortw/tweetmoasharp/issues/76

**Comment by Yortw** [comment]
Closing on the assumption @collinsauve was correct, and no follow up from OP.
