### ISSUE TITLE
Problem with Hammock.WinRT.dll

### ISSUE THREAD

**Issue by kacperbranicki** [Yortw/tweetmoasharp#8]
Hi, I have noticed a problem with TweetMoaSharp nuget package. I have installed it from nuget repo, it's working fine, but when I created an appx package of my Windows Phone 8.1 project, it can't pass tests form Windows App Certification Kit. The is a problem with Hammock.WinRT.dll because it is build in debug mode rather than release mode. Can you provide my a release version of Hammock.WinRT.dll or change it in nuget package?
Kacper

**Comment by Yortw** [comment]
Hi,

I think I've fixed the problem, and I have pushed a new Nuget package, but I haven't had time to confirm it works. Please let me know if there are further issues.

Thanks.
