### ISSUE TITLE
URL Shortening -- not working?

### ISSUE THREAD

**Issue by scorpionmit01** [Yortw/tweetmoasharp#9]
Supposed to check help/configuration to know how many characters are available for shortening, I can't figure out how to access that via TweetSharp, so I'm estimating a few more than currently used.

However, when I pass the status with a longer URL, it should auto-shorten according to Twitter Dev, but I'm getting Error 186, too long.

Any advice for where to look?

**Comment by Yortw** [comment]
Off the top of my head no. I'll try to check later when I'm home from work, but TBH I'm not sure TweetSharp actually exposes stuff like the url length/max media count etc. It probably should though.

Very odd that you get an error back from Twitter saying the url is too long - so far as I'm aware they're supposed to do the shortening on their end. Can you provide a sample tweet & url?

**Comment by Yortw** [comment]
I've added support in the latest code and nuget package for calling the help/configuration endpoint and retrieving the metadata. I haven't had time to look at your other issue, a sample of the text & link you're having trouble tweeting would help. Thanks.

**Comment by Yortw** [comment]
Closing this issue as the new endpoint has been implemented, and no feed back on other problem (which probably deserves to be a separate issue anyway).
